@echo off
echo Setting up Visual Studio Build Environment...
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
echo Environment ready. Starting build...

npm run build && pake ./dist/index.html --name Hearken --use-local-file